insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10001,'Diego', 'Roel', 'Madrid', 'Spain');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10002,'Marie', 'Bertrand', 'Paris', 'France');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10003,'Patricio', 'Simpson', 'Buenos Aires', 'Argentina');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10004,'Paolo', 'Accorti', 'Torino', 'Italy');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10005,'Pascale', 'Cartrain', 'Charleroi', 'Belgium');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10006,'Maurizio', 'Moroni', 'Reggio Emilia', 'Italy');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10007,'Yvonne', 'Moncada', 'Buenos Aires', 'Argentina');
insert into CUSTOMER (ID, FIRST_NAME, LAST_NAME, CITY, COUNTRY) values(10008,'Fran', 'Wilson', 'Portland', 'USA');
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(100, 542912, 12.50, 10003);
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(101, 542937, 18.40, 10004);
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(102, 542897, 28.00, 10005);
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(103, 542716, 28.00, 10006);
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(104, 543028, 30.00, 10007);
insert into CUSTOMER_ORDER (ID, ORDER_NUMBER, TOTAL_AMOUNT, CUSTOMER_ID) values(105, 543013, 36.00, 10008);